version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      firebase-tooling:
        patterns:
          - firebase
          - firebase-tools
          - "@firebase/*"

  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
